In [37]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
#create a random tensor of size(3,3)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [39]:
#create a random tensor with similar size and shape of an image
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [40]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
###creating a range of tensor and tensors like
#using torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
one_to_ten=torch.arange(start=0,end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

**Tensor Data type**
**Note:Tensor datatypes is one of the 3 big erors you'll run into with pytorch and deep learng**
1.Tensors not right datatype
2.tensors not right shape
3.tensors not on the right device

In [44]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False
                             )
float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dtype

torch.float32

In [46]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [47]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [48]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [49]:
int_32_tensor*int_32_tensor

tensor([ 9, 36, 81], dtype=torch.int32)

Getting information from tensor
1Tensors not right datatype -to get datatype from tensor we use tensor.dtype
2.tensors not right shape -to get shape from tensor we use tensor.shape
3.tensors not on the right device -to get device information we use tensor.device


In [50]:
#create tensor
some_tensor=torch.rand(3,2)
some_tensor

tensor([[0.5745, 0.9200],
        [0.3230, 0.8613],
        [0.0919, 0.3102]])

In [51]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.5745, 0.9200],
        [0.3230, 0.8613],
        [0.0919, 0.3102]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 2])
Device tensor is on:cpu


manupulating tensors (tensor operation)
Tensor operations include:
1.Addition
2.Substraction
3.Multiplication(element-Wise)
4.Division
5.Matrix multiplication

In [52]:
#create a tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [53]:
#multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [54]:
#substract
tensor-10

tensor([-9, -8, -7])

In [55]:
 #try out Pytorch in-built functions
 torch.mul(tensor,10)

tensor([10, 20, 30])

Two main way of perfoming multiplication in neural networks and eep learninf:

1.Element-Wise multiplication
2.Mtrix mutliplication(dot product)
more infomation about matrix mutliplication:https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [56]:
#Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equel:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equel:tensor([1, 4, 9])


In [57]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

*Find the positional min and max*

In [58]:
#create a tensor
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
#tensor wiht mini value position
x.argmin()

tensor(0)

In [61]:
#tensor position with max
x.argmax()

tensor(9)

PyTorch Tennsor and NumPy
Numpy is a popular scientific python umerical cumputation library.
Ad because of this , PyTorch has functionality to interact with it
.Data in NumPy , want in yTorch tensor->torch.from_numpy(ndarray)
.pyTorch tensor->NumPy->torch.Tensor.numpt()

In [62]:
import torch
import numpy as np
#convert array to tnsor
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [63]:
tensor.dtype

torch.float32

In [64]:
#Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))



**Reproducebility(trying to take random out of random)**
In short how  neural network learns:
'start with random number->tensor operation->upate random number to make them better representation of the data->again->again->again....'

To reduce the randomness in neural networks and PyTorch comes the concept of a **Random seed.**

Essentially what the random seed does is "flavor" the randomness

In [65]:
import torch

#create random tensor
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])
tensor([[0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726],
        [0.5194, 0.5337, 0.7050, 0.3362]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [66]:
 #Let's make some random but reproducible
 import torch

 #Set the random seed

 RANDOM_SEED=42
 torch.manual_seed(RANDOM_SEED)
 random_tensor_C=torch.rand(3,4)

 torch.manual_seed(RANDOM_SEED)
 random_tensor_D=torch.rand(3,4)

 print(random_tensor_C)
 print(random_tensor_D)
 print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and pyTorch on the GPU (and making faster computation)
GPU=faster computation on number to CUDA+NVIDIA hardware +PyTorch working behind the scene to make everything hunky dory(good)


In [67]:
!nvidia-smi

Fri Mar  8 14:20:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

check GPU access in Pytorch

In [72]:
import torch
torch.cuda.is_available()

True

Setup device agnostic code

In [74]:
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [75]:
#count number of device
torch.cuda.device_count()

1

Putting tensors(and Models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU result in faster computation

In [76]:
#create a tensor (default on the cpu)
tensor=torch.tensor([1,2,3],device="cpu")

#tensor not in GPU

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [77]:
#move tensor to GPU (if is available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')